export interface VSearchResult {
	key: string;
	similarity: number;
	metadata?: Record<string, unknown>;
}

export interface TSSample {
	timestamp: number;
	value: number;
}

export interface TSAddOptions {
	retention?: number;
	labels?: Record<string, string>;
}

export interface TSRangeOptions {
	aggregation?: {
		type: 'avg' | 'sum' | 'min' | 'max' | 'count' | 'first' | 'last' | 'range' | 'std.p' | 'std.s' | 'var.p' | 'var.s';
		bucketSize: number;
	};
}

export interface TSMRangeResult {
	key: string;
	labels: Record<string, string>;
	samples: TSSample[];
}

export interface KSubEvent {
	pattern: string;
	key: string;
	operation: string;
}

export interface TableRow {
	id?: number | string;
	[field: string]: unknown;
}

export type LuxInferRow<T> = T extends readonly (infer Row)[] ? Row : T;

export type LuxTypedRow<T> = LuxInferRow<T> extends object
	? LuxInferRow<T>
	: TableRow;

/**
 * A project's schema: a map of table name -> row type. Generated by `lux types`
 * (the `Database` type). Pass it to `createClient<Database>()` so
 * `client.table('table')` infers the row type and autocompletes table names.
 * The default is an open index so untyped clients keep working.
 */
export type LuxSchema = Record<string, Record<string, unknown>>;

export type LuxAggregateValue = number | string;

export type LuxAggregateRow<Aliases extends string = string> = Record<Aliases, LuxAggregateValue>;

export interface LuxSimilarity {
	_similarity: number | string;
}

export type LuxNearRow<T extends object = Record<string, unknown>> = T & LuxSimilarity;

export interface LuxError {
	code: string;
	message: string;
	details?: unknown;
}

export type LuxResult<T> = {
	data: T;
	error: null;
} | {
	data: null;
	error: LuxError;
}

type SchemaSafeParse<T> = { success: true; data: T } | { success: false; error: unknown };

export interface TableSchema<T> {
	parse?: (input: unknown) => T;
	safeParse?: (input: unknown) => SchemaSafeParse<T>;
}

export type TableChangeType = 'insert' | 'update' | 'delete' | 'change' | 'error';

export interface TableChangeEvent<T extends object = TableRow> {
	type: Exclude<TableChangeType, 'error'>;
	table: string;
	pk: string;
	operation: string;
	new: T | null;
	old: T | null;
	changed?: string[];
	raw?: KSubEvent;
}

export interface TableErrorEvent {
	type: 'error';
	table: string;
	error: LuxError;
}
